default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: double-quote-string-fixer

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.2
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: __init__.py
        args: ["--ignore=E501"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
