version: '3.9'

networks:
  test_network:
    external:
      name: menu_app_network

services:
  test_menu_app:
    container_name: test_menu_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_USER: 'admin1'
      PG_PASSWORD: 'admin111'
      PG_HOST: 'app_db'
      PG_PORT: 5432
      PG_DB: 'app_db'
      API_URL: 'http://menu_app:8000/api/v1'
    command: 'pytest -vv'
    networks:
      - test_network
