version: '3.9'

services:
  test_db:
    image: postgres:latest
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin1'
      POSTGRES_DB: 'test_db'

