version: '3.9'

networks:
  another_network:
    name: another_network


services:
  test_menu_app:
    container_name: test_menu_up
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_USER: 'admin000'
      PG_PASSWORD: 'admin000'
      PG_HOST: 'test_db'
      PG_PORT: 5432
      PG_DB : 'test_db'
    entrypoint: >
      sh -c "
        echo 'Starting app now' &&
        echo 'we are ready' &&
        uvicorn main:menu_app --host 0.0.0.0 --reload
      "
    networks:
      - another_network
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      test_db:
        condition: service_healthy


  test_db:
    container_name: test_db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: 'admin000'
      POSTGRES_PASSWORD: 'admin000'
      POSTGRES_DB: 'test_db'
    ports:
      - '5433:5432'
    networks:
      - another_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin000 -d test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_USER: 'admin000'
      PG_PASSWORD: 'admin000'
      PG_HOST: 'test_db'
      PG_PORT: 5432
      PG_DB: 'test_db'
      API_URL: 'http://test_menu_up:8000/api/v1'
    command: 'pytest -vv'
    networks:
      - another_network
    depends_on:
      - test_menu_app